import type { Dataset, Dashboard, Metric, Notification, Workflow, ActivityItem, AuditLog, Plugin } from "@/types";

export const mockMetrics: Metric[] = [
  { label: "Total Revenue", value: 2847593, change: 12.5, changeType: "increase", prefix: "$" },
  { label: "Active Users", value: 48291, change: 8.2, changeType: "increase" },
  { label: "Data Processed", value: "2.4 TB", change: 23.1, changeType: "increase" },
  { label: "AI Queries", value: 12847, change: 45.3, changeType: "increase" },
  { label: "Dashboards", value: 342, change: 5.7, changeType: "increase" },
  { label: "Forecast Accuracy", value: "94.2%", change: 2.1, changeType: "increase" },
];

export const mockDatasets: Dataset[] = [
  {
    id: "ds-1",
    name: "Sales Transactions Q4",
    description: "Quarterly sales data across all regions",
    type: "csv",
    size: 245000000,
    rows: 1250000,
    columns: 24,
    status: "active",
    quality: 96,
    lastUpdated: "2026-07-30T10:00:00Z",
    createdBy: "Sarah Chen",
    tags: ["sales", "quarterly", "revenue"],
  },
  {
    id: "ds-2",
    name: "Customer Analytics",
    description: "Customer behavior and segmentation data",
    type: "parquet",
    size: 890000000,
    rows: 4500000,
    columns: 42,
    status: "active",
    quality: 91,
    lastUpdated: "2026-07-29T15:30:00Z",
    createdBy: "Marcus Johnson",
    tags: ["customers", "analytics", "segmentation"],
  },
  {
    id: "ds-3",
    name: "Supply Chain Metrics",
    description: "Real-time supply chain performance indicators",
    type: "sql",
    size: 156000000,
    rows: 890000,
    columns: 18,
    status: "processing",
    quality: 88,
    lastUpdated: "2026-07-31T08:00:00Z",
    createdBy: "Elena Rodriguez",
    tags: ["supply-chain", "operations"],
  },
  {
    id: "ds-4",
    name: "Marketing Campaign ROI",
    description: "Campaign performance and attribution data",
    type: "json",
    size: 78000000,
    rows: 320000,
    columns: 15,
    status: "active",
    quality: 94,
    lastUpdated: "2026-07-28T12:00:00Z",
    createdBy: "David Kim",
    tags: ["marketing", "roi", "campaigns"],
  },
  {
    id: "ds-5",
    name: "Financial Forecasts",
    description: "Historical and projected financial data",
    type: "csv",
    size: 45000000,
    rows: 180000,
    columns: 32,
    status: "active",
    quality: 97,
    lastUpdated: "2026-07-27T09:00:00Z",
    createdBy: "Sarah Chen",
    tags: ["finance", "forecasting"],
  },
];

export const mockDashboards: Dashboard[] = [
  {
    id: "dash-1",
    name: "Executive Overview",
    description: "C-suite KPI dashboard with real-time metrics",
    widgets: 12,
    views: 4821,
    lastModified: "2026-07-30T14:00:00Z",
    createdBy: "Sarah Chen",
    isPublic: false,
    tags: ["executive", "kpi"],
  },
  {
    id: "dash-2",
    name: "Sales Performance",
    description: "Regional sales tracking and pipeline analysis",
    widgets: 8,
    views: 2340,
    lastModified: "2026-07-29T11:00:00Z",
    createdBy: "Marcus Johnson",
    isPublic: true,
    tags: ["sales", "regional"],
  },
  {
    id: "dash-3",
    name: "Customer Health Score",
    description: "Customer satisfaction and retention metrics",
    widgets: 6,
    views: 1890,
    lastModified: "2026-07-28T16:00:00Z",
    createdBy: "Elena Rodriguez",
    isPublic: false,
    tags: ["customers", "health"],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n-1",
    title: "Dataset Processing Complete",
    message: "Sales Transactions Q4 has been successfully processed and profiled.",
    type: "success",
    read: false,
    createdAt: "2026-07-31T10:30:00Z",
    actionUrl: "/datasets/ds-1",
  },
  {
    id: "n-2",
    title: "AI Insight Generated",
    message: "New anomaly detected in Customer Analytics dataset.",
    type: "info",
    read: false,
    createdAt: "2026-07-31T09:15:00Z",
    actionUrl: "/insights",
  },
  {
    id: "n-3",
    title: "Workflow Failed",
    message: "Daily ETL pipeline encountered an error at step 3.",
    type: "error",
    read: true,
    createdAt: "2026-07-30T22:00:00Z",
    actionUrl: "/workflows",
  },
  {
    id: "n-4",
    title: "New Team Member",
    message: "David Kim joined your workspace.",
    type: "info",
    read: true,
    createdAt: "2026-07-30T14:00:00Z",
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Daily ETL Pipeline",
    description: "Extract, transform, and load daily sales data",
    status: "active",
    triggers: 1,
    lastRun: "2026-07-31T06:00:00Z",
    nextRun: "2026-08-01T06:00:00Z",
    successRate: 98.5,
  },
  {
    id: "wf-2",
    name: "Weekly Report Generator",
    description: "Generate and distribute weekly analytics reports",
    status: "active",
    triggers: 1,
    lastRun: "2026-07-28T08:00:00Z",
    nextRun: "2026-08-04T08:00:00Z",
    successRate: 100,
  },
  {
    id: "wf-3",
    name: "Anomaly Detection",
    description: "Real-time anomaly detection across all datasets",
    status: "active",
    triggers: 3,
    lastRun: "2026-07-31T11:00:00Z",
    successRate: 95.2,
  },
  {
    id: "wf-4",
    name: "Data Quality Check",
    description: "Automated data quality validation",
    status: "paused",
    triggers: 2,
    lastRun: "2026-07-25T12:00:00Z",
    successRate: 92.8,
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: "a-1",
    type: "dataset",
    title: "Dataset uploaded",
    description: "Financial Forecasts was uploaded by Sarah Chen",
    user: "Sarah Chen",
    timestamp: "2026-07-31T10:00:00Z",
  },
  {
    id: "a-2",
    type: "dashboard",
    title: "Dashboard updated",
    description: "Executive Overview was modified by Marcus Johnson",
    user: "Marcus Johnson",
    timestamp: "2026-07-31T09:30:00Z",
  },
  {
    id: "a-3",
    type: "ai",
    title: "AI query executed",
    description: "Natural language query on Customer Analytics",
    user: "Elena Rodriguez",
    timestamp: "2026-07-31T09:00:00Z",
  },
  {
    id: "a-4",
    type: "workflow",
    title: "Workflow completed",
    description: "Daily ETL Pipeline finished successfully",
    user: "System",
    timestamp: "2026-07-31T06:00:00Z",
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "al-1",
    action: "LOGIN",
    resource: "Authentication",
    user: "Sarah Chen",
    timestamp: "2026-07-31T10:30:00Z",
    ip: "192.168.1.100",
    status: "success",
  },
  {
    id: "al-2",
    action: "DATA_EXPORT",
    resource: "Sales Transactions Q4",
    user: "Marcus Johnson",
    timestamp: "2026-07-31T09:45:00Z",
    ip: "192.168.1.105",
    status: "success",
  },
  {
    id: "al-3",
    action: "PERMISSION_CHANGE",
    resource: "Customer Analytics",
    user: "Sarah Chen",
    timestamp: "2026-07-31T09:00:00Z",
    ip: "192.168.1.100",
    status: "success",
  },
  {
    id: "al-4",
    action: "LOGIN_FAILED",
    resource: "Authentication",
    user: "unknown@example.com",
    timestamp: "2026-07-30T23:15:00Z",
    ip: "10.0.0.55",
    status: "failure",
  },
];

export const mockPlugins: Plugin[] = [
  {
    id: "pl-1",
    name: "Snowflake Connector",
    description: "Connect and sync data from Snowflake warehouses",
    version: "2.4.1",
    author: "NexusBI",
    category: "Connectors",
    installed: true,
    rating: 4.8,
    downloads: 12500,
  },
  {
    id: "pl-2",
    name: "Advanced Forecasting",
    description: "Prophet and ARIMA forecasting models",
    version: "1.8.0",
    author: "NexusBI Labs",
    category: "Analytics",
    installed: true,
    rating: 4.6,
    downloads: 8900,
  },
  {
    id: "pl-3",
    name: "Slack Integration",
    description: "Send alerts and reports to Slack channels",
    version: "3.1.2",
    author: "Community",
    category: "Integrations",
    installed: false,
    rating: 4.5,
    downloads: 6700,
  },
  {
    id: "pl-4",
    name: "Geo Analytics",
    description: "Advanced geospatial visualization and analysis",
    version: "1.2.0",
    author: "NexusBI Labs",
    category: "Visualization",
    installed: false,
    rating: 4.7,
    downloads: 4200,
  },
];

export const chartData = {
  revenue: [
    { month: "Jan", value: 420000, forecast: 410000 },
    { month: "Feb", value: 480000, forecast: 465000 },
    { month: "Mar", value: 520000, forecast: 510000 },
    { month: "Apr", value: 580000, forecast: 560000 },
    { month: "May", value: 620000, forecast: 605000 },
    { month: "Jun", value: 680000, forecast: 650000 },
    { month: "Jul", value: 720000, forecast: 700000 },
  ],
  users: [
    { month: "Jan", active: 32000, new: 4200 },
    { month: "Feb", active: 34500, new: 3800 },
    { month: "Mar", active: 36800, new: 4100 },
    { month: "Apr", active: 39200, new: 4500 },
    { month: "May", active: 42100, new: 4800 },
    { month: "Jun", active: 45200, new: 5200 },
    { month: "Jul", active: 48291, new: 5500 },
  ],
  categories: [
    { name: "Enterprise", value: 45 },
    { name: "Mid-Market", value: 28 },
    { name: "SMB", value: 18 },
    { name: "Startup", value: 9 },
  ],
};
